services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: passport-pal-backend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/public/samples:/app/frontend/public/samples
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0  # Enable GPU if available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - passportpal-network

  frontend:
    build:
      context: ./frontend
    container_name: passport-pal-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/public/samples:/usr/share/nginx/html/samples
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - passportpal-network

networks:
  passportpal-network:
    driver: bridge
